CREATE TABLE STUDENTS(
    ID INT UNIQUE,
    NAME VARCHAR(50) NOT NULL,
    GENDER VARCHAR NOT NULL,
    MARKS INT CHECK(MARKS >= 35),
    STATUS VARCHAR(50) DEFAULT 'NOT VACCINATED'
);

INSERT INTO STUDENTS
VALUES(514, 'NIGA1', 'M', 43, 'VACCINATED'),
(122, 'NIGA2', 'F', 69, DEFAULT);

SELECT * FROM STUDENTS;